import type { Metadata } from "next";
import "./globals.css";
import { ChatProvider } from "@/contexts/ChatContext";


export const metadata: Metadata = {
  title: "EletroFarias",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        {/* Importação dos Ícones (Resolve o problema do "light_mode" aparecendo como texto) */}
        <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap" rel="stylesheet" />
      </head>
      <body
        className="antialiased"
      >
        <ChatProvider>{children}</ChatProvider>
      </body>
    </html>
  );
} 

